version: '3'

services:
  # 开发环境配置
  app-dev:
    image: node:18.12.1-alpine
    container_name: soil-platform-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install && npm run serve"

  # 生产环境配置
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME:-username}/soil-platform:latest
    container_name: soil-platform-prod
    ports:
      - "80:80"
    restart: unless-stopped 